### ISSUE TITLE
Feature Request: Non-www to www redirect support. 

### ISSUE THREAD

**Issue by samhamilton** [citrus/spree_redirects#2]
It would be great if this extension could support a non-www to www and www to non-www depending on the administrators preference.

**Comment by iloveitaly** [comment]
Although this is something that could be added to this extension, I think this is a better fit as a configuration setting in your HTTP server (more performant if done on the HTTP server level). [Here is how you would set this up on nginx](https://github.com/spree/deployment_service_puppet/pull/3).
